title: WebX Specification
description: The modern WebX Specification.

baseurl: "/"

theme: just-the-docs
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template