title: WebX Specification
description: The modern WebX Specification.

url: "https://spec.webxplus.org"
baseurl: "/"

theme: just-the-docs
color_scheme: dark
heading_anchors: true

callouts:
  deprecated:
    title: Deprecated
    color: red

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true